name: Publish Package

env:
  module_id: iforgor
  qmodName: IForgor
  cache-name: iforgor_cache

on:
  push:
    tags:
      - 'v*'

permissions:
  pull-requests: write
  contents: write
  repository-projects: write # add permission for forking

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: true
          lfs: true

      - uses: seanmiddleditch/gha-setup-ninja@v3



      # Use canary NDK to avoid lesser known compile bugs
      - name: Setup canary NDK
        id: setup-ndk
        uses: ./.github/actions/canary-ndk

      - name: Create ndkpath.txt
        run: |
          echo ${{ steps.setup-ndk.outputs.ndk-path }} > ${GITHUB_WORKSPACE}/ndkpath.txt
          cat ${GITHUB_WORKSPACE}/ndkpath.txt
      # - name: Create ndkpath.txt
      #   run: |
      #     echo "$ANDROID_NDK_LATEST_HOME" > ${GITHUB_WORKSPACE}/ndkpath.txt
      #     cat ${GITHUB_WORKSPACE}/ndkpath.txt

      - name: Get Tag Version
        id: get_tag_version
        run: |
          echo ${GITHUB_REF#refs/tags/}
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}
          qpm s build

      - name: Create Qmod
        run: |
          qpm qmod zip

      - name: Get Library Name
        id: libname
        run: |
          cd ./build/
          pattern="lib${module_id}*.so"
          files=( $pattern )
          echo ::set-output name=NAME::"${files[0]}"

      - name: Rename debug
        run: |
          mv ./build/debug/${{ steps.libname.outputs.NAME }} ./build/debug/debug_${{ steps.libname.outputs.NAME }}


      - name: Create Qmod
        run: |
          pwsh -Command ./scripts/createqmod.ps1 ${{env.qmodName}}

      - name: Upload to Release
        id: upload_file_release
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: ${{ github.event.inputs.release_msg }}
          tag_name: ${{ github.event.inputs.version }}
          files: |
            ./${{ env.qmodName }}.qmod
            ./build/${{ steps.libname.outputs.NAME }}
            ./build/debug/debug_${{ steps.libname.outputs.NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make PR to QeatMods3
        id: qmod-release
        uses: QuestPackageManager/qmod-repo-publish-action@main
        # TODO: Make this work!
        continue-on-error: true
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          # first asset URL
          qmod_url: ${{ fromJSON(steps.upload_file_release.outputs.assets)[0].browser_download_url }}
          qmod_repo_owner: 'dantheman827'
          qmod_repo_name: 'bsqmods'